# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to handle arena rewards for users

Globals:
    Function:
        Environment:
            Variables:
                SQS_URL: !Ref SaveArenaRewardsQueue

Resources:
    SaveArenaRewardsQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: deferred-save-arena-rewards-queue
            VisibilityTimeout: 601
    RetrieveArenaRewardsFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve-arena-rewards.default
            Runtime: nodejs16.x
            CodeUri: ./dist/retrieve-arena-rewards
            Timeout: 5
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-retrieve-arena-rewards-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
    StartSaveArenaRewardsFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: start-save-arena-rewards.default
            Runtime: nodejs16.x
            CodeUri: ./dist/start-save-arena-rewards
            Timeout: 5
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-start-save-arena-rewards-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
    ProcessSaveArenaRewardsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-save-arena-rewards.default
            Runtime: nodejs16.x
            CodeUri: ./dist/process-save-arena-rewards
            MemorySize: 128
            ReservedConcurrentExecutions: 1
            Layers:
                - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-save-arena-rewards
            Timeout: 60
            Events:
                SQSMapperRequestedEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SaveArenaRewardsQueue.Arn
                        # BatchSize: 1
